@startuml
title: All schemas
footer: Common Gateway Plugin | Commongateway | Vrijbrptozgwbundle 
header: Schema
class CloudEvent {
  + specversion: string
  + id: string
  + source: string
  + type: string
  + datacontenttype: string
  + data: array
}
@enduml
