@startuml
title: Notification
footer: Common Gateway Plugin | Commongateway | Vrijbrptozgwbundle 
header: Schema

class Notification {
  + specversion: string
  + id: string
  + source: string
  + type: string
  + datacontenttype: string
  + data: array
}
@enduml
